sudo: required
language: python
python:
  - '2.7'

addons:
  apt:
    packages:
    - sshpass
services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - python tests.py

before_install:
  - docker --version
  - docker build -t $DOCKER_USERNAME/simple_flask_app:latest .
  - docker images
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy_key.enc -out ./deploy_key -d

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/simple_flask_app:latest
  - export SSHPASS=$DEPLOY_PASS

deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && sshpass -e ssh -o StrictHostKeyChecking=no -i ./deploy_key
    $HOST@$HOST_IP './deploy.sh'
  on:
    branch: master
env:
  global:
  - secure: oG9smHjJed07gDRv+PJOzPDbs5a+LVdAl+z/kCLtbkiz3I4hhhkHl2M4Lj1PhgxzryJVZEB2H6/I8G3dHhFsGDyipcIJWitl7UBU7P4cMw+VuGLaWtS7T2LGbUO8GOebiyNXFWpWQfQJAeioaRUrioBaAsoJaJMKRf1bxht3t1xIBb8B2JhQP4TSdWAk2TEd3Ejp76bba8+ekABiByw42h91Ub6fzxHA2bgsFqbCtTXRPfZTLd9suSrakOyw5ajWAIcV7ypU6LdmVN6Cw0cXfWU7eFdB5woSp1A66RJD3XSSIRTTBkx6yH0ac9RvhWFT86HcLUgw79CxaqyE176JR9jpRw0PA2AYLl2C69OSfI+uC3IctufoxCuQ/7rFHAgof3F2mHDiS7gRF3fvPL4iPYIP2x0cDkH5QQgmfhDZXXfrcrr5MOF0C7YvfQoSMN3Ar2srvbQ+ir/Yb2p1w96Z0motUV4XIYynrB9LCjIa/eiFjfaHDQFM8mx7S7jK+WapwoRZhMp9Nb7HSewBE/V7JYKPsG+YSvA0CdB93pajKm0txZyYcESq3sDkFg3GxOScplrNW05tvWZese1BTb1XOYAqBrFRjuhdQ2GiBGNRbWiKWRnOIh4uc+iVPtwhO/GPEm7tiRKuwvYfsZBDzjyYIL9BfGM7j61AYEaiWiuWXaM=
  - secure: sstGgrtK9IBPxXYXJzKHHfkJ7rI6DykyAyOl65JwYyuAXupjBHiiij5qlY5QPu8d1aCDaovFzM5IwdUvxhZOHNPldkokSEG8DYG2e7Fwh88Qzg+Uqr0pPlqKc3Ag9kEJdc5UB7YzAwSuomHyStNWtHqelynnF1QCGi04kFQzYWFJ0FVBdH/SHWfWZfd3V+akbqUo/t8IQRSSmoqboc7jeupkYWmwBnhl30iMOo8EZYZ454cZ2iyRXsv9yvELEk88pwyZ9Gk5FOaMZJDK/gIR7uI0aqmFiZuvhGI3AbQC1jtLQ8Kd2YwB0w5RjZNIVtAdxw2PBop+mrEZQDLGKqzM+FKvo3XRP4kZTxY3tYsZjFHu0ULyEXSxFM/1IAGwaSuRlcjvTAnGjWywFrT+GjVX03sWOEDXzqGznR9vFUsxhrNqQJ9MMm5jfy7DHxrbnyfODijfLZSPBPisITuqCUKDXroINHH9auGBACwHgzvDeNXg27ElPdPT/eZ8XgRFsKzku/0qepF7eglyyheTpaRtk+IlQdviUERnFO75aQf9ME+wyLueJikMqtvtvcz+mMEMuhKkKRFkMfqd+fH3p+6AYBZtTUy8ZZrnEkP3ygCuHKIXnNfUcNqN1OU3QhjuyUUmfLoxb8FSkFze3zJzk9KD6bB1c9+cMC/QSmTdfgcnOxo=
  - secure: QRyS/xAoOoBJzRkUkCzPomkHtQxu90kG3HFxsRHi/LAA+2SYyFkG2ylwLiQYwzjmcORBZY9yEjlmMA10nfWTK2JtQP8rm9QgwKuLtAKs0turqaNnJFnEOsTlFFuyww/OP1H37AJ7+Cm2wR8TZO4sqAXtAa7XL0Jnyl7PQpkBS5Gu62lFozYjz58cFn8XDx+He3qi3Uk3CiwXPKcQw3oCNwve3/5/wRQRMJ4X9CKsy5bt4DiRVjIuXpQSV4hYaqiX0LIygUUp87+k7yLSbGZX9T8yRmVSwZQUAkP1771Wc3zsJbiDuOdQHwESgXcaS+AcDPXC6sBz/wGLlAlbPafZ6NI8kDN7hzkb0J+4lz4c4QY++TBWmrEfRiWRVdFwLTIbbNknkc70UsbO+bf5Uztu44XcIEG6k2DBHlp7xt1Z22oiZzacy1fyagEGxXVY0vNDYYxd05FdsTdQ4xdC4p5n3cNh/isFazb5KOaWU6e016RgYn6TvwxDP2elO2MLdwTr+oRR2YkCjVHcrSUpeqiqCEJOyvXy0vPkSdFvK7cnT7M5ws/TvK7raA2j6hQkRZlX/tcwFO1Rb21CnybobwQMXTEcwh660qHN03j6xgH6v/jza7dBHncOmEuWcQmL4+q3srW9q/NJXfUETcMNomz8nhKVmL/rTqEB7xiTROSzAFo=
  - secure: dCKVU0SOA9rUbJiCmlK1mEJ6k8h0wkwY66V5ssvLXAJiGFph2XEFg5c82klG9CWDCPqce80fliJz70ClylsS1znRLx6oj2nr4WMDmQx8hblaBkzz960kap+gLXNsz6fZHVkyUyjq5GW9jyEVdjpFKdt78H+VZBWy087AaPi+FEGtb5gcH+rPLifwPWqCxt5FM4d7+3sASgLdVQ2YFEcp/TgJ6W33GaHGd8lztcOsfQmyx8xlsukxBppSssafEeCqg8QzjG8spBrCFcxVpbg7Gluie9Dkj+Z73aq0s126r33CjjQyCnJZCIUMUSXkvVHSyKu7Q8aFkz+xEqoKe/k/8jJO4bvL22wF22ibMYqf2caV4QxhcuYbR4u4VAPnJloxowzXs4V0XWWv9GTAR49Ez2JSUv695UW5HfiZEpRViKhFbul+tZgVLwaFq0541rbQ3ilC1ZjnZQ+VlzJfrd5kIuaTc18o5NLxQJNhB+FuP8UJiJrExx6dZlIgPydhVYrRos5VhT89mHxQcYSAJ09GhtnS6cZo4dCcBoJ3MToJ8qygkkfo4C+ryxsYstVJT+vPKZR0vwPGgw1UTVQtZRGqsB0vJDIfLteTWO0Jzo/BSrop2HnlocVWbi/1qriJ6dtqXz124wUaqOZTCHtGP8fI6AMh9GUvuflHLrmKsRQ2c/k=
  - secure: MLj8DTL05VwIpl5nFjqdaMB0h2hFJpQEXevH/lZ5vTFSLnxkiFxBXkvgcEkqKYyFwH2Dr7Rbi4riPPx+QRcjLQHavZBZIfI9kauzXsi/ji2qGtQw8AMgBkRxBBMFrB2ODlZQWMSgZZWsXNVhawQ9ZgCb7ofGfFtFCz4LlpOgDzSHj1DsYDsaRBPo68+LECDwjq1Ayd4zknXLP3cXeOYGA0KZBrZZvXwuHD09vKLIsgDBMSJaQGMgYwSAlqJUVpTqcHhJAe4QMVpo7MSc5GHc+b/38jxbtGpcvNzzq1/ftXp4pQLM3HDrNr+InBu18cOrKik4XBhdeYBjrZASZDUqOxKmE/wxOYLKl+ghVQOKEPdf2PTzjSM+86Kszmf04cHS5+B/dbRGxlQFaYjFOuTM2whJo5eL1TcLYmqFE2Bv6OoISr+CV0/9MiHjwGSA03AwST53APKbuTp8iMvWRkSmqCr2wYEOjBARiJprV29DbFUiK2UpXH3NomoD1ViENDphDrMg8tkr+opweCfecg3SuBrG1KumQKEjDHyLLS7P9fk3yvsY/BUOGM5M/fZHnHh97H3FGRdiLMQDHp2p8ulxyLAsxpWv2rxkEmAu7m3eo+SiT/yuRycAWl2Yrr01D20x11gMD4tRHldS/In/hwilRG7lMhtWFLgrG01HM6n/g/k=
